from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',views.hompepageview,name='homepage'),
    path('admin/',views.adminloginview,name='adminloginpage'),
    path('userlogin/',views.userloginview,name='userloginpage'),
    path('faq/',views.faqview),
    path('about/',views.aboutandcontactview),
    path('authenticateadmin/',views.authenticateadmin),
    path('admin/homepage/',views.adminhomepageview,name='adminhomepage'),
    path('admin/logout/',views.logoutadmin),
    path('signupuser/',views.signup),
    path('user/authenticate/',views.userauthenticate),
    path('user/homepage/',views.userhomepageview,name='userhomepage'),
    path('user/logout/',views.userlogout),
    path('user/getlisted/',views.getlistedview,name='getlisted'),
    path('user/getlisted/submit/',views.getlistedformsubmit),
    path('user/getlisted/status/',views.submissionstatus,name='submissionstatus'),
    path('usersignup/',views.signupview,name="signup"),
    path('resetpassword/',views.resetpasswordview,name='resetpassword'),
    path('reset/',views.reset),
    path('user/profile/',views.profilepage),
    path('search/',views.searchview,name="search"),
    path('admin/listingrequests/',views.adminrequests,name='approvalrequests'),
    path('admin/addshop/',views.adminaddshopview),
    path('admin/addshop/submit/',views.adminaddshops,name='adminaddshop'),
    path('admin/userqueries/',views.userqueries,name="adminqueries"),
    path('listingapprove/<int:listingpk>/',views.listingapprove),
    path('listingreject/<int:listingpk>/',views.listingreject),
    path('searchresult/',views.searchresult),
    path('searchprofile/<int:profilepk>/',views.searchprofile),
    path('contactus/',views.contactview,name="contactus"),
    path('querysubmit/',views.querysubmit),
    path('getdetails/',views.getdetails),
    path('admin/locations/',views.adminlocations,name="editlocations"),
    path('addlocation/',views.addlocation),
    path('deletelocality/<int:deletepk>/',views.deletelocality),
    path('deletecity/<int:deletepk>/',views.deletecity),
    path('responded/<int:querypk>/',views.queryresponded),
    path('deletequery/<int:querypk>/',views.querydelete),
]
