# Generated by Django 3.1.4 on 2021-05-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('securityquestion', models.CharField(max_length=50)),
                ('securityanswer', models.CharField(max_length=50)),
            ],
        ),
    ]
