# Generated by Django 3.1.4 on 2021-05-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmartapp', '0002_getlisted'),
    ]

    operations = [
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('locality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='searchdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('locality', models.CharField(max_length=30)),
                ('shopname', models.CharField(max_length=100)),
                ('shopaddress', models.CharField(max_length=500)),
                ('shopcontact', models.CharField(max_length=12)),
                ('shopimage', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
