# Generated by Django 3.1.4 on 2021-05-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmartapp', '0004_auto_20210514_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='status',
            field=models.CharField(default='NOT RESPONDED', max_length=20),
        ),
    ]
