# Generated by Django 3.1.4 on 2021-05-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapmartapp', '0005_userquery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchdb',
            name='shopimage',
            field=models.ImageField(upload_to='searchdb/'),
        ),
    ]
